// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace JoyconQuat
{
    internal static unsafe partial class NativeMethod
    {
        const string __DllName = "joycon_quat_native";



        /// <summary>
        ///  # Safety
        ///  buffer_ptr は 18byte の 加速度を除いた情報を詰める必要がある。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "quaternion_parse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern QuaternionParseResultFFI quaternion_parse(byte* buffer_ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct QuaternionParseResultFFI
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_ok;
        public QuaternionFFI zero;
        public QuaternionFFI one;
        public QuaternionFFI two;
        public TimestampFFI time_stamp;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct QuaternionFFI
    {
        public float x;
        public float y;
        public float z;
        public float w;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TimestampFFI
    {
        public ushort start;
        public byte count;
    }



}
